### ISSUE TITLE
Difference from PFLD-pytorch

### ISSUE THREAD

**Issue by xuguozhi** [ideask/A-Practical-Facial-Landmark-Detector#1]
Hi, is there any difference between this implementation and [this one](PFLD-pytorch) ?
Any updated code?

**Comment by ideask** [comment]
加了多GPU训练，改了一下模型结构，retrain了一下

**Comment by xuguozhi** [comment]
> 改了一下模型结构

针对速度优化还是精度呢？提升了哪些？

**Comment by ideask** [comment]
你可以看看论文，原论文用的是dw conv，没做专业上的对比，不知道性能和速度有什么提升，只是想尽量还原论文的结构试一下。您可以做个对比？

**Comment by xuguozhi** [comment]
> 你可以看看论文，原论文用的是dw conv，没做专业上的对比，不知道性能和速度有什么提升，只是想尽量还原论文的结构试一下。您可以做个对比？

好的，我试下比较，稍后把结果放上来

**Comment by xuguozhi** [comment]
WFLW test results：
PFLD-pytorch：
2.8 ms
`NME 0.246 ION 3.99`
 this repo：
2.8ms
`NME 0.420 ION 7.213`
模型都是pretrained的，是训练不充分的原因吗。速度差不多

**Comment by ideask** [comment]
感觉dw conv会丢失一些精度，也有可能是我训练不充分，你试下自己跑一下？
